export const ONE_SECOND_IN_MILLISECONDS = 1000;
export const BARBARIAN_SPAWN_INTERVAL_SECONDS = 60;
export const BARBARIAN_BASE_SPAWN_COUNT = 1;
export const BARBARIAN_POP_PER_CAMP = 10;
export const BARBARIAN_ATTACK_INTERVAL_SECONDS = 5;
export const BARBARIAN_TROOPS_PER_CAMP = 10;
