export const ONE_SECOND_IN_MILLISECONDS = 1000;

// buildings
export const BUILDINGS_DEFAULT_VISION = 1
export const BUILDINGS_LONG_VISION = 3
export const BUILDINGS_BASE_DEFAULT_HEALTH = 500
export const BUILDINGS_OUTPOST_BASE_HEALTH = 1000
export const BUILDINGS_CAPITAL_BASE_HEALTH = 1200
export const BUILDINGS_FORTIFICATIONS_BASE_HEALTH = 1200
export const BUILDINGS_BARBARIAN_CAMPS_BASE_HEALTH = 600
export const BUILDINGS_CAPITAL_BASE_COST = 250
export const BUILDINGS_BASE_DEFAULT_COST = 50
export const BUILDINGS_BASE_HIGH_COST = 150
export const BUILDINGS_CAPITAL_BASE_CAPACITY = 100
export const BUILDINGS_BASE_DEFAULT_CAPACITY = 50
export const BUILDINGS_HEALTH_EXPONENTIAL_FACTOR = 2
export const BUILDINGS_COST_EXPONENTIAL_FACTOR = 3
export const BUILDINGS_CAPACITY_LINEAR_INCREMENT = 50
export const BUILDINGS_PRODUCTION_EXPONENTIAL_FACTOR = 2
export const BUILDINGS_BASE_PRODUCTION = 1

// barbarians
export const BARBARIAN_SPAWN_INTERVAL = 60;
export const BARBARIANS_BUILDINGS_CAMP_RATIO = 10;
export const BARBARIAN_ATTACK_INTERVAL = 1;
export const BARBARIAN_TROOPS_PER_CAMP = 5;
export const BARBARIAN_COLOR = "#C0392B";

// ages
export const AGE_MAX = 10;
export const AGE_BASE_SCIENCE_COST = 100;

// players
export const PLAYER_COLORS = [
    "#E67E22",
    "#A04000",
    "#D4AC0D",
    "#B7950B",
    "#F1C40F",
    "#9A7D0A",
    "#27AE60",
    "#1E8449",
    "#138D75",
    "#145A32",
    "#2980B9",
    "#1F618D",
    "#154360",
    "#2471A3",
    "#8E44AD",
    "#7D3C98",
    "#9B59B6",
    "#A569BD",
]